INSERT INTO user_stories (title, description, status, created_at, updated_at, acceptance_criteria, story_points,
                          priority, epic_id, tags, project_id)
VALUES ('As a user, I want to log in to my account', 'To be able to access personalized features', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'User provides valid credentials and is authenticated', 5, 1, 1,
        'authentication,security', 1),
       ('As a user, I want to view my profile', 'To see my personal information', 'TO_DO', CURRENT_TIMESTAMP, NULL,
        'User can see their name, email, and profile picture', 3, 2, 1, 'profile,user-interface', 1),
       ('As an admin, I want to manage user accounts', 'To create, edit, and delete user accounts', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'Admin can create, edit, and delete user accounts', 8, 1, 1, 'admin,user-management',
        1),
       ('As a user, I want to browse the product catalog', 'To find products I might want to purchase', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'User can see a list of products with descriptions and prices', 4, 2, 2,
        'product,user-interface', 1),
       ('As a user, I want to view product details', 'To learn more about a specific product', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'User can see detailed product information, including images and specifications', 3, 2,
        2, 'product,user-interface', 1),
       ('As a user, I want to search for products', 'To quickly find specific products', 'TO_DO', CURRENT_TIMESTAMP,
        NULL, 'User can search for products by name or keywords', 5, 2, 2, 'product,search', 1),
       ('As a user, I want to add products to my cart', 'To save products I want to purchase', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'User can add products to a shopping cart', 4, 2, 2, 'cart,checkout', 1),
       ('As a user, I want to make a payment', 'To purchase the items in my cart', 'TO_DO', CURRENT_TIMESTAMP, NULL,
        'User can enter payment information and complete the purchase', 5, 1, 3, 'payment,checkout', 1),
       ('As an admin, I want to view sales reports', 'To track sales performance', 'TO_DO', CURRENT_TIMESTAMP, NULL,
        'Admin can see reports on sales revenue, order volume, and top-selling products', 7, 1, 4,
        'reporting,analytics', 1),
       ('As a user, I want to use the mobile application', 'To access the features on my phone', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'User can access the main features of the application on a mobile device', 6, 2, 5,
        'mobile,user-interface', 1),
       ('As a developer, I want to implement chat feature', 'To allow users to communicate with each other', 'TO_DO',
        CURRENT_TIMESTAMP, NULL, 'Users can send and receive messages in real-time', 8, 2, 5, 'mobile,chat', 1),
       ('As a developer, I want to implement report generation', 'To allow admin and other roles to generate reports',
        'TO_DO', CURRENT_TIMESTAMP, NULL, 'System can generate reports in PDF and Excel formats', 7, 2, 4,
        'reporting,generation', 1);
