name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Lint and Build frontend
      - name: Lint and Build Frontend
        run: |
          cd frontend
          npm install
          npm run lint
          npm run build

  java:
    name: Java Build (JDK 17)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        # Build file-export module
      - name: Build File Export Module with Maven
        run: mvn -B install --file file-export/pom.xml
        # Build ai integration
      - name: Build AI Integration Service with Maven
        run: mvn -B package --file ai-integration/pom.xml
        # Build task service
      - name: Build Task Service with Maven
        run: mvn -B package --file task-service/pom.xml
        # Build gateway service
      - name: Build Gateway Service with Maven
        run: mvn -B package --file gateway-service/pom.xml
        # Build mail service
      - name: Build Mail Service with Maven
        run: mvn -B package --file mail-sender/pom.xml
        # Build authorization service
      - name: Build Authorization Service with Maven
        run: mvn -B package --file auth-service/pom.xml
